let productList = {
  Burgers: [
    {
      itemCode: "B1001",
      name: "Classic Burger",
      price: 1500.0,
      discount: 0,
      isEmpty: false,
    },
    {
      itemCode: "B1002",
      name: "Turkey Burger",
      price: 1600.0,
      discount: 15,
      isEmpty: false,
    },
    {
      itemCode: "B1003",
      name: "Chicken Burger",
      price: 1400.0,
      discount: 0,
      isEmpty: false,
    },
    {
      itemCode: "B1004",
      name: "Cheese Chicken Burger",
      price: 1000.0,
      discount: 5,
      isEmpty: false,
    },
    {
      itemCode: "B1005",
      name: "Crispy Chicken Burger",
      price: 1200.0,
      discount: 0,
      isEmpty: false,
    },
    {
      itemCode: "B1006",
      name: "Special Olive Burger",
      price: 1800.0,
      discount: 5,
      isEmpty: false,
    },
    {
      itemCode: "B1007",
      name: "Bacon Burger",
      price: 650.0,
      discount: 0,
      isEmpty: false,
    },
    {
      itemCode: "B1008",
      name: "Shawarma Burger",
      price: 800.0,
      discount: 12,
      isEmpty: false,
    },
    {
      itemCode: "B1009",
      name: "Double Cheese Burger",
      price: 1250.0,
      discount: 20,
      isEmpty: false,
    },
    {
      itemCode: "B1010",
      name: "Paneer Burger",
      price: 900.0,
      discount: 0,
      isEmpty: false,
    },
  ],
  Submarines: [
    {
      itemCode: "B10011",
      name: "Double Cheese Chicken Submarine",
      price: 1900.0,
      discount: 16,
    },
    {
      itemCode: "B10012",
      name: "MOS Special Submarine",
      price: 3000.0,
      discount: 0,
    },
    {
      itemCode: "B10013",
      name: "Special Horgie Submarine",
      price: 2300.0,
      discount: 0,
    },
    {
      itemCode: "B10014",
      name: "Cheese Submarine",
      price: 2200.0,
      discount: 0,
    },
    {
      itemCode: "B10015",
      name: "Chicken Submarine",
      price: 2000.0,
      discount: 0,
    },
    {
      itemCode: "B10016",
      name: "Grinder Submarine",
      price: 2300.0,
      discount: 0,
    },
    {
      itemCode: "B10017",
      name: "Crispy Chicken Submarine",
      price: 1500.0,
      discount: 0,
    },
  ],
  Pasta: [
    {
      itemCode: "B10018",
      name: "Chicken Cheese Pasta",
      price: 1600.0,
      discount: 15,
    },
    {
      itemCode: "B10019",
      name: "Chicken Penne Pasta",
      price: 1700.0,
      discount: 0,
    },
    {
      itemCode: "B10020",
      name: "Ground Turkey Pasta Bake",
      price: 2900.0,
      discount: 10,
    },
    {
      itemCode: "B10021",
      name: "Creamy Shrimp Pasta",
      price: 2000.0,
      discount: 0,
    },
    {
      itemCode: "B10022",
      name: "Lemon Butter Pasta",
      price: 1950.0,
      discount: 0,
    },
    {
      itemCode: "B10023",
      name: "Tagliatelle Chicken Pasta",
      price: 2400.0,
      discount: 1,
    },
    {
      itemCode: "B10024",
      name: "Baked Ravioli",
      price: 2000.0,
      discount: 1,
    },
  ],
  Fries: [
    {
      itemCode: "B10025",
      name: "Steak Fries",
      price: 1200.0,
      discount: 0,
    },
    {
      itemCode: "B10026",
      name: "French Fries",
      price: 800.0,
      discount: 0,
    },
    {
      itemCode: "B10027",
      name: "Potato Fries",
      price: 600.0,
      discount: 0,
    },
  ],

  Chicken: [
    {
      itemCode: "B10028",
      name: "Fried Chicken",
      price: 1200.0,
      discount: 0,
    },
    {
      itemCode: "B10029",
      name: "BBQ Chicken",
      price: 2100.0,
      discount: 0,
    },
    {
      itemCode: "B10030",
      name: "Devilled Chicken",
      price: 900.0,
      discount: 0,
    },
    {
      itemCode: "B10031",
      name: "Hot Wings",
      price: 2400.0,
      discount: 5,
    },
  ],
  Beverages: [
    {
      itemCode: "B10032",
      name: "Pepsi (330ml)",
      price: 990.0,
      discount: 2,
    },
    {
      itemCode: "B10033",
      name: "Coca-Cola (330ml)",
      price: 1230.0,
      discount: 0,
    },
    {
      itemCode: "B10034",
      name: "Sprite (330ml)",
      price: 1500.0,
      discount: 3,
    },
    {
      itemCode: "B10035",
      name: "Mirinda (330ml)",
      price: 850.0,
      discount: 7,
    },
  ],
};

export let list = productList;
