// let productList = {
//   Burgers: [
//     {
//       itemCode: "B1001",
//       name: "Classic Burger",
//       price: 1500.0,
//       discount: 0,
//       description: "A timeless classic with fresh ingredients.",
//     },
//     {
//       itemCode: "B1002",
//       name: "Turkey Burger",
//       price: 1600.0,
//       discount: 15,
//       description: "Delicious turkey patty with crisp veggies.",
//     },
//     {
//       itemCode: "B1003",
//       name: "Chicken Burger",
//       price: 1400.0,
//       discount: 0,
//       description: "Juicy chicken patty with tangy sauce.",
//     },
//     {
//       itemCode: "B1004",
//       name: "Cheese Chicken Burger",
//       price: 1000.0,
//       discount: 5,
//       description: "Chicken burger topped with creamy cheese.",
//     },
//     {
//       itemCode: "B1005",
//       name: "Crispy Chicken Burger",
//       price: 1200.0,
//       discount: 0,
//       description: "Crispy fried chicken in a soft bun.",
//     },
//     {
//       itemCode: "B1006",
//       name: "Special Olive Burger",
//       price: 1800.0,
//       discount: 5,
//       description: "Unique burger with fresh olives added.",
//     },
//     {
//       itemCode: "B1007",
//       name: "Bacon Burger",
//       price: 650.0,
//       discount: 0,
//       description: "Classic burger with crispy bacon strips.",
//     },
//     {
//       itemCode: "B1008",
//       name: "Shawarma Burger",
//       price: 800.0,
//       discount: 12,
//       description: "A fusion of burger and shawarma flavors.",
//     },
//     {
//       itemCode: "B1009",
//       name: "Double Cheese Burger",
//       price: 1250.0,
//       discount: 20,
//       description: "Double cheese layers for ultimate satisfaction.",
//     },
//     {
//       itemCode: "B1010",
//       name: "Paneer Burger",
//       price: 900.0,
//       discount: 0,
//       description: "Soft paneer patty with spices and sauce.",
//     },
//   ],
//   Submarines: [
//     {
//       itemCode: "B10011",
//       name: "Double Cheese Chicken Submarine",
//       price: 1900.0,
//       discount: 16,
//       description: "Packed with chicken and double cheese layers.",
//     },
//     {
//       itemCode: "B10012",
//       name: "MOS Special Submarine",
//       price: 3000.0,
//       discount: 0,
//       description: "Loaded with special ingredients for flavor.",
//     },
//     {
//       itemCode: "B10013",
//       name: "Special Horgie Submarine",
//       price: 2300.0,
//       discount: 0,
//       description: "A unique submarine with a savory taste.",
//     },
//     {
//       itemCode: "B10014",
//       name: "Cheese Submarine",
//       price: 2200.0,
//       discount: 0,
//       description: "Creamy cheese-filled submarine delight.",
//     },
//     {
//       itemCode: "B10015",
//       name: "Chicken Submarine",
//       price: 2000.0,
//       discount: 0,
//       description: "Juicy chicken-filled submarine sandwich.",
//     },
//     {
//       itemCode: "B10016",
//       name: "Grinder Submarine",
//       price: 2300.0,
//       discount: 0,
//       description: "Hearty submarine with rich grinder flavors.",
//     },
//     {
//       itemCode: "B10017",
//       name: "Crispy Chicken Submarine",
//       price: 1500.0,
//       discount: 0,
//       description: "Submarine with crispy chicken perfection.",
//     },
//   ],
//   Pasta: [
//     {
//       itemCode: "B10018",
//       name: "Chicken Cheese Pasta",
//       price: 1600.0,
//       discount: 15,
//       description: "Cheesy pasta with tender chicken chunks.",
//     },
//     {
//       itemCode: "B10019",
//       name: "Chicken Penne Pasta",
//       price: 1700.0,
//       discount: 0,
//       description: "Rich penne pasta paired with chicken.",
//     },
//     {
//       itemCode: "B10020",
//       name: "Ground Turkey Pasta Bake",
//       price: 2900.0,
//       discount: 10,
//       description: "Baked pasta with seasoned turkey and cheese.",
//     },
//     {
//       itemCode: "B10021",
//       name: "Creamy Shrimp Pasta",
//       price: 2000.0,
//       discount: 0,
//       description: "Pasta with shrimp in a creamy sauce.",
//     },
//     {
//       itemCode: "B10022",
//       name: "Lemon Butter Pasta",
//       price: 1950.0,
//       discount: 0,
//       description: "Pasta tossed in fresh lemon butter sauce.",
//     },
//     {
//       itemCode: "B10023",
//       name: "Tagliatelle Chicken Pasta",
//       price: 2400.0,
//       discount: 1,
//       description: "Tagliatelle pasta with tender chicken mix.",
//     },
//     {
//       itemCode: "B10024",
//       name: "Baked Ravioli",
//       price: 2000.0,
//       discount: 1,
//       description: "Baked ravioli with cheese and tomato sauce.",
//     },
//   ],
//   Fries: [
//     {
//       itemCode: "B10025",
//       name: "Steak Fries",
//       price: 1200.0,
//       discount: 0,
//       description: "Thick and crispy steak-cut potato fries.",
//     },
//     {
//       itemCode: "B10026",
//       name: "French Fries",
//       price: 800.0,
//       discount: 0,
//       description: "Classic golden fries with crispy edges.",
//     },
//     {
//       itemCode: "B10027",
//       name: "Potato Fries",
//       price: 600.0,
//       discount: 0,
//       description: "Simple yet delicious potato fries treat.",
//     },
//   ],

//   Chicken: [
//     {
//       itemCode: "B10028",
//       name: "Fried Chicken",
//       price: 1200.0,
//       discount: 0,
//       description: "Crispy fried chicken with juicy inside.",
//     },
//     {
//       itemCode: "B10029",
//       name: "BBQ Chicken",
//       price: 2100.0,
//       discount: 0,
//       description: "Tender chicken with smoky BBQ sauce.",
//     },
//     {
//       itemCode: "B10030",
//       name: "Devilled Chicken",
//       price: 900.0,
//       discount: 0,
//       description: "Spicy and tangy devilled chicken dish.",
//     },
//     {
//       itemCode: "B10031",
//       name: "Hot Wings",
//       price: 2400.0,
//       discount: 5,
//       description: "Spicy hot wings with flavorful sauce.",
//     },
//   ],
//   Beverages: [
//     {
//       itemCode: "B10032",
//       name: "Pepsi (330ml)",
//       price: 990.0,
//       discount: 2,
//       description: "Classic Pepsi to refresh your taste buds.",
//     },
//     {
//       itemCode: "B10033",
//       name: "Coca-Cola (330ml)",
//       price: 1230.0,
//       discount: 0,
//       description: "Coca-Cola, the iconic fizzy beverage.",
//     },
//     {
//       itemCode: "B10034",
//       name: "Sprite (330ml)",
//       price: 1500.0,
//       discount: 3,
//       description: "Refreshing lemon-lime soda with crisp taste",
//     },
//     {
//       itemCode: "B10035",
//       name: "Mirinda (330ml)",
//       price: 850.0,
//       discount: 7,
//       description: "Vibrant orange soda with fruity flavor",
//     },
//   ],
// };
let productList = {
  Burgers: [
    {
      itemCode: "B1001",
      name: "Classic Burger",
      price: 1500.0,
      discount: 0,
      description: "A timeless classic with fresh ingredients.",
      imgUrl: "img/burgers/b1.png",
    },
    {
      itemCode: "B1002",
      name: "Turkey Burger",
      price: 1600.0,
      discount: 15,
      description: "Delicious turkey patty with crisp veggies.",
      imgUrl: "img/burgers/b2.png",
    },
    {
      itemCode: "B1003",
      name: "Chicken Burger",
      price: 1400.0,
      discount: 0,
      description: "Juicy chicken patty with tangy sauce.",
      imgUrl: "img/burgers/b3.png",
    },
    {
      itemCode: "B1004",
      name: "Cheese Chicken Burger",
      price: 1000.0,
      discount: 5,
      description: "Chicken burger topped with creamy cheese.",
      imgUrl: "img/burgers/b4.png",
    },
    {
      itemCode: "B1005",
      name: "Crispy Chicken Burger",
      price: 1200.0,
      discount: 0,
      description: "Crispy fried chicken in a soft bun.",
      imgUrl: "img/burgers/b5.png",
    },
    {
      itemCode: "B1006",
      name: "Special Olive Burger",
      price: 1800.0,
      discount: 5,
      description: "Unique burger with fresh olives added.",
      imgUrl: "img/burgers/b2.png",
    },
    {
      itemCode: "B1007",
      name: "Bacon Burger",
      price: 650.0,
      discount: 0,
      description: "Classic burger with crispy bacon strips.",
      imgUrl: "img/burgers/b1.png",
    },
    {
      itemCode: "B1008",
      name: "Shawarma Burger",
      price: 800.0,
      discount: 12,
      description: "A fusion of burger and shawarma flavors.",
      imgUrl: "img/burgers/b5.png",
    },
    {
      itemCode: "B1009",
      name: "Double Cheese Burger",
      price: 1250.0,
      discount: 20,
      description: "Double cheese layers for ultimate satisfaction.",
      imgUrl: "img/burgers/b3.png",
    },
    {
      itemCode: "B1010",
      name: "Paneer Burger",
      price: 900.0,
      discount: 0,
      description: "Soft paneer patty with spices and sauce.",
      imgUrl: "img/burgers/b4.png",
    },
  ],
  Submarines: [
    {
      itemCode: "B10011",
      name: "Double Cheese Chicken Submarine",
      price: 1900.0,
      discount: 16,
      description: "Packed with chicken and double cheese layers.",
      imgUrl: "img/submarines/s1.png",
    },
    {
      itemCode: "B10012",
      name: "MOS Special Submarine",
      price: 3000.0,
      discount: 0,
      description: "Loaded with special ingredients for flavor.",
      imgUrl: "img/submarines/s2.png",
    },
    {
      itemCode: "B10013",
      name: "Special Horgie Submarine",
      price: 2300.0,
      discount: 0,
      description: "A unique submarine with a savory taste.",
      imgUrl: "img/submarines/s3.png",
    },
    {
      itemCode: "B10014",
      name: "Cheese Submarine",
      price: 2200.0,
      discount: 0,
      description: "Creamy cheese-filled submarine delight.",
      imgUrl: "img/submarines/s4.png",
    },
    {
      itemCode: "B10015",
      name: "Chicken Submarine",
      price: 2000.0,
      discount: 0,
      description: "Juicy chicken-filled submarine sandwich.",
      imgUrl: "img/submarines/s1.png",
    },
    {
      itemCode: "B10016",
      name: "Grinder Submarine",
      price: 2300.0,
      discount: 0,
      description: "Hearty submarine with rich grinder flavors.",
      imgUrl: "img/submarines/s2.png",
    },
    {
      itemCode: "B10017",
      name: "Crispy Chicken Submarine",
      price: 1500.0,
      discount: 0,
      description: "Submarine with crispy chicken perfection.",
      imgUrl: "img/submarines/s4.png",
    },
  ],
  Pasta: [
    {
      itemCode: "B10018",
      name: "Chicken Cheese Pasta",
      price: 1600.0,
      discount: 15,
      description: "Cheesy pasta with tender chicken chunks.",
      imgUrl: "img/pasta/p1.jpg",
    },
    {
      itemCode: "B10019",
      name: "Chicken Penne Pasta",
      price: 1700.0,
      discount: 0,
      description: "Rich penne pasta paired with chicken.",
      imgUrl: "img/pasta/p2.jpg",
    },
    {
      itemCode: "B10020",
      name: "Ground Turkey Pasta Bake",
      price: 2900.0,
      discount: 10,
      description: "Baked pasta with seasoned turkey and cheese.",
      imgUrl: "img/pasta/p3.jpg",
    },
    {
      itemCode: "B10021",
      name: "Creamy Shrimp Pasta",
      price: 2000.0,
      discount: 0,
      description: "Pasta with shrimp in a creamy sauce.",
      imgUrl: "img/pasta/p4.jpg",
    },
    {
      itemCode: "B10022",
      name: "Lemon Butter Pasta",
      price: 1950.0,
      discount: 0,
      description: "Pasta tossed in fresh lemon butter sauce.",
      imgUrl: "img/pasta/p5.jpg",
    },
    {
      itemCode: "B10023",
      name: "Tagliatelle Chicken Pasta",
      price: 2400.0,
      discount: 1,
      description: "Tagliatelle pasta with tender chicken mix.",
      imgUrl: "img/pasta/p2.jpg",
    },
    {
      itemCode: "B10024",
      name: "Baked Ravioli",
      price: 2000.0,
      discount: 1,
      description: "Baked ravioli with cheese and tomato sauce.",
      imgUrl: "img/pasta/p1.jpg",
    },
  ],
  Fries: [
    {
      itemCode: "B10025",
      name: "Steak Fries",
      price: 1200.0,
      discount: 0,
      description: "Thick and crispy steak-cut potato fries.",
      imgUrl: "img/fries/f1.png",
    },
    {
      itemCode: "B10026",
      name: "French Fries",
      price: 800.0,
      discount: 0,
      description: "Classic golden fries with crispy edges.",
      imgUrl: "img/fries/f2.png",
    },
    {
      itemCode: "B10027",
      name: "Potato Fries",
      price: 600.0,
      discount: 0,
      description: "Simple yet delicious potato fries treat.",
      imgUrl: "img/fries/f3.png",
    },
  ],

  Chicken: [
    {
      itemCode: "B10028",
      name: "Fried Chicken",
      price: 1200.0,
      discount: 0,
      description: "Crispy fried chicken with juicy inside.",
      imgUrl: "img/chicken/c3.png",
    },
    {
      itemCode: "B10029",
      name: "BBQ Chicken",
      price: 2100.0,
      discount: 0,
      description: "Tender chicken with smoky BBQ sauce.",
      imgUrl: "img/chicken/c2.png",
    },
    {
      itemCode: "B10030",
      name: "Devilled Chicken",
      price: 900.0,
      discount: 0,
      description: "Spicy and tangy devilled chicken dish.",
      imgUrl: "img/chicken/c5.png",
    },
    {
      itemCode: "B10031",
      name: "Hot Wings",
      price: 2400.0,
      discount: 5,
      description: "Spicy hot wings with flavorful sauce.",
      imgUrl: "img/chicken/c4.png",
    },
  ],
  Beverages: [
    {
      itemCode: "B10032",
      name: "Pepsi (330ml)",
      price: 990.0,
      discount: 2,
      description: "Classic Pepsi to refresh your taste buds.",
      imgUrl: "img/beverages/pepsi.png",
    },
    {
      itemCode: "B10033",
      name: "Coca-Cola (330ml)",
      price: 1230.0,
      discount: 0,
      description: "Coca-Cola, the iconic fizzy beverage.",
      imgUrl: "img/beverages/cola.png",
    },
    {
      itemCode: "B10034",
      name: "Sprite (330ml)",
      price: 1500.0,
      discount: 3,
      description: "Refreshing lemon-lime soda with crisp taste.",
      imgUrl: "img/beverages/sprite.png",
    },
    {
      itemCode: "B10035",
      name: "Mirinda (330ml)",
      price: 850.0,
      discount: 7,
      description: "Vibrant orange soda with fruity flavor.",
      imgUrl: "img/beverages/mirinda.png",
    },
  ],
};

export let list = productList;
